name: Release

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup .npmrc file for publish
              uses: actions/setup-node@v2
              with:
                  node-version: '12'
                  registry-url: 'https://registry.npmjs.org'

            - name: Get yarn cache directory path
              id: yarn-cache-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Configure Git User
              run: |
                  git config --global user.email "development@mariomh.com"
                  git config --global user.name "$GITHUB_ACTOR"

            - name: Install dependencies
              run: yarn install

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: yarn release
                  commit: 'chore: release'
                  title: 'Release'
                  setupGitUser: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
